
env:
  IMAGE_NODE: chain-proxy
  REGISTRY_HOSTNAME: terradharitri

name: Build Docker image & push

on:
  release:
    types: [published]
  pull_request:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git history

      - name: Get version info
        id: version
        run: |
          VERSION=$(git describe --tags --long --dirty || echo "v0.0.0-dev")
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NODE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION }}
            COMMIT_SHA=${{ steps.version.outputs.COMMIT_SHA }}